//
//  StyleKit.h
//  Hunch
//
//  Created by Anthony Picciano on 1/28/15.
//  Copyright (c) 2015 Anthony Picciano. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Colors
+ (UIColor*)hunchYellow;
+ (UIColor*)hunchRed;
+ (UIColor*)hunchLightBlue;
+ (UIColor*)hunchDarkViolet;
+ (UIColor*)hunchDarkIndigo;
+ (UIColor*)hunchOrange;
+ (UIColor*)hunchDeepPurple;
+ (UIColor*)hunchDeepBlue;
+ (UIColor*)hunchLightGreen;
+ (UIColor*)hunchBlue;
+ (UIColor*)hunchTurquoise;
+ (UIColor*)hunchWhite;

// Drawing Methods
+ (void)drawAnswerLabelWithFrame: (CGRect)frame background: (UIImage*)background answer: (NSString*)answer;

@end
