//
//  StyleKit.h
//  Hunch
//
//  Created by Anthony Picciano on 1/27/15.
//  Copyright (c) 2015 Anthony Picciano. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawAnswerLabelWithFrame: (CGRect)frame background: (UIImage*)background answer: (NSString*)answer;

@end
